### PR TITLE
Added support for IPaymentPlugin to be able to handle SerializedCart

### PR DESCRIPTION
**Pull request by mbooh**
Added extra property setting for default value for checkbox for newsletter in Klarna Checkout

### CODE REVIEW

**Comment by marisks** [comment]
The commit looks ok except for that newsletter checkbox. 
At first, it should be a separate commit and pull request. Then the question is why it is needed? I couldn't find any info about such newsletter checkbox in the Klarna documentation. I only saw the description of "custom checkbox" which could be used for newsletter or something else: https://developers.klarna.com/en/de/kco-v2/checkout/extra-features

**Comment by mbooh** [comment]
Ok, maybe we can skip it then? I actually thought it was used for newsletter only.
What do you think?

/Kristoffer

Från: Māris Krivtežs [mailto:notifications@github.com]
Skickat: den 16 november 2017 11:33
Till: Geta/EPi.Commerce.Payments <EPi.Commerce.Payments@noreply.github.com>
Kopia: Kristoffer Lindén <kristoffer.linden@authority.se>; Author <author@noreply.github.com>
Ämne: Re: [Geta/EPi.Commerce.Payments] Added support for IPaymentPlugin to be able to handle SerializedCart (#40)


The commit looks ok except for that newsletter checkbox.
At first, it should be a separate commit and pull request. Then the question is why it is needed? I couldn't find any info about such newsletter checkbox in the Klarna documentation. I only saw the description of "custom checkbox" which could be used for newsletter or something else: https://developers.klarna.com/en/de/kco-v2/checkout/extra-features

**Comment by marisks** [comment]
Yes, please remove this from this pull request.

**Comment by mbooh** [comment]
Pull request is updated.

/Kristoffer

Från: Māris Krivtežs [mailto:notifications@github.com]
Skickat: den 16 november 2017 11:37
Till: Geta/EPi.Commerce.Payments <EPi.Commerce.Payments@noreply.github.com>
Kopia: Kristoffer Lindén <kristoffer.linden@authority.se>; Author <author@noreply.github.com>
Ämne: Re: [Geta/EPi.Commerce.Payments] Added support for IPaymentPlugin to be able to handle SerializedCart (#40)


Yes, please remove this from this pull request.

**Pull request merged**
